branches :
  only:
    -main
language: node_js
node_js:
  - 13

services:
 - docker

install:
 - echo "nothing needs to be installed"

#test scripts
before_script:
  - echo "no tests."

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  #tags
  - docker tag  udagram-reversproxy muhammmedessa/udagram-reverseproxy:v7
  - docker tag  udagram-api-feed    muhammmedessa/udagram-api-feed:v7
  - docker tag  udagram-api-user    muhammmedessa/udagram-api-user:v7
  - docker tag  udagram-frontend    muhammmedessa/udagram-frontend:v7

  #tasks
  after_success:
    - echo "DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
    - docker push muhammmedessa/udagram-reverseproxy:v7
    - docker push muhammmedessa/udagram-api-feed:v7
    - docker push muhammmedessa/udagram-api-user:v7
    - docker push muhammmedessa/udagram-frontend:v7