branches:
  only:
    - main
language: node_js
node_js:
  - 13

services:
  - docker


install:
  - echo "nothing needs to be installed"


before_script:
  - echo "no tests"

script:
  - docker --version 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag  udagram-api-feed    muhammmedessa/udagram-api-feed-de:v9
  - docker tag  udagram-api-user    muhammmedessa/udagram-api-user-de:v9
  - docker tag  reverseproxy muhammmedessa/reverseproxy-de:v9
  - docker tag  udagram-frontend    muhammmedessa/udagram-frontend-de:v9

after_success:
  - echo "DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
  - docker push muhammmedessa/udagram-api-feed-de:v9
  - docker push muhammmedessa/udagram-api-user-de:v9
  - docker push muhammmedessa/reverseproxy-de:v9
  - docker push muhammmedessa/udagram-frontend-de:v9