apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzENH//////////wEaDLxITsoK8/o7g3/PpSK7ATo84XL/E/Ta6kfeJfGfthLlL6CshcPOkbkptscfYJ+YPQHgg+/bde1TyVtmTnsT0wtmOt/qUA7uIiByx+8k/+nrH3fGFUxxzXm9rkaoTc9uneFwJxVQvuWbNJJwnv3xXbYK6zYX3XW60kS9jASHK2POhy5XlzapgFULWXkbwu8luWI/JJoa8TyHRkfjTefbW2u2TNr0FxRgW9L3BhqCv2Mm78mYm+uT05CSgy13fQNKb6/i3rHahYSGOyMo9N2ZmgYyLW8vDwQSXOKHjBGkXJK3T/e1sClOiRvIr107sW0NoeVHGUnkCOs6sbUW+AsB0Q==